server.port=${PORT:9000}

spring.datasource.url=jdbc:mysql://irkm0xtlo2pcmvvz.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/ahf1268r64dw86bj?useSSL=false&serverTimezone=UTC
spring.datasource.username=f1w77pk21665cdp9
spring.datasource.password=q727tmrwgnhqdzi3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt_secret=jk1frC45